apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hid-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sgosukonda82/argocd.git
    targetRevision: HEAD
    path: hid/dev
    
  destination: 
    server: https://kubernetes.default.svc
    namespace: hid-dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true