apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hid-qa
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sgosukonda82/argocd.git
    targetRevision: HEAD
    path: hid/qa

  destination: 
    server: https://kubernetes.default.svc
    namespace: hid-qa

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true