# Replace all the {{}} except {{TAG}} variable to customize the template
# {{TAG}} will be replaced by the release scripts
# Image name, Deployment Instance or host path may be reuqired to change for the cloud and on-prem based on the git hub structure
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -hid-{{envname}}
resources:
  - ../../../../../base/hidsafeweb
  - ../hpa

images:
    - name: hidsafeweb-image
      newName: localhost:32000/safe/hid.iams.unob.adn8.0.safeweb
      newTag: {{TAG}}

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hidsafeweb
        namespace: {{clientname}}-{{envname}}
        labels:
          namespace-name: '{{clientname}}-{{envname}}'
          deployment-env: '{{envname}}'
          deployment-instance: 'local'
          enable-hidsafeweb: 'y'
      spec:
        selector:
          matchLabels:
            namespace-name: '{{clientname}}-{{envname}}'
            deployment-env: '{{envname}}'
            deployment-instance: 'local'
            enable-hidsafeweb: "y"
        template:
          metadata:
            labels:
              namespace-name: '{{clientname}}-{{envname}}'
              deployment-env: '{{envname}}'
              deployment-instance: 'local'
              enable-hidsafeweb: 'y'
          spec:
            containers:
            - name: hidsafeweb
              env:
              - name: ASPNETCORE_Kestrel__Certificates__Default__Path
                value: /app/certs/AGServerCert.crt 
              - name: ASPNETCORE_Kestrel__Certificates__Default__KeyPath
                value: /app/certs/AGServerCertSecEncKey.pem
            volumes:
            - name: config-volume
              hostPath:
                path: /usr/local/share/source/repos/safe_vnext/Src//Container/config
            - name: log-volume
              hostPath:
                path: /usr/local/share/runlogs
            - name: cert-volume
              hostPath:
                path: /usr/local/share/ncerts
            - name: cert-key-volume
              hostPath:
                path: /usr/local/share/ncerts/certkey
          
  - target:
      kind: Service
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: hidsafeweb
        namespace: {{clientname}}-{{envname}}
        labels:
          namespace-name: '{{clientname}}-{{envname}}'
          deployment-env: '{{envname}}'
          deployment-instance: 'local'
          enable-ext-ip-for-hidsafeweb: 'y'
          use-pool: hidsafekiosk-ext-ip-pool-in-dev
      spec:
        sessionAffinityConfig:
          clientIP:
            timeoutSeconds: 60
        selector:
            namespace-name: '{{clientname}}-{{envname}}'
            deployment-env: '{{envname}}'
            deployment-instance: 'local'
        loadBalancerIP: ''

  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      apiVersion: v1
      kind: HorizontalPodAutoscaler
      metadata:
        name: hidsafeweb-hpa
        namespace: {{clientname}}-{{envname}}
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: hidsafeweb-hid-{{envname}}

  - target:
      kind: Job
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: hidsafeweb-presync-status
        labels:
          namespace-name: '{{clientname}}-{{envname}}'
          deployment-env: '{{envname}}'
          deployment-instance: 'local'
      spec:
        template:
          spec:
            containers:
            - name: presync-status-container
              env:
              - name: CLIENT
                value: "{{clientname}}"
              - name: ENV
                value: "{{envname}}"