apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: argocd
  labels:
    namespace-name: ''
    deployment-env: ''
    deployment-instance: ''
    client_name: ''
spec:
  project: default
  sources: []
  source:
    repoURL: ''
    path: .
    targetRevision: ''
  destination:
    name: ''
    namespace: ''
    server: ''
  syncPolicy:
    retry:
      limit: 60
      backoff:
        duration: 60s
        factor: 1
        maxDuration: 120s
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true