# Replace all the {{}} except {{TAG}} variable to customize the template
# {{TAG}} will be replaced by the release scripts
# Image name, Deployment Instance or host path may be reuqired to change for the cloud and on-prem based on the git hub structure
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -hid-qa
resources:
  - ../../../../../base/secrets

patches:
  - target:
      kind: Secret
    patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: safeapp-credentials
        namespace: hid-qa
        labels:
          namespace-name: 'hid-qa'
          deployment-env: 'qa'
          deployment-instance: 'local'
      data:
        username: c2FmZXJhYmJpdA==
        password: c2FmZXJhYmJpdA==
