# Replace all the {{}} except {{TAG}} variable to customize the template
# {{TAG}} will be replaced by the release scripts
# Image name, Deployment Instance or host path may be reuqired to change for the cloud and on-prem based on the git hub structure
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -hid-{{envname}}
resources:
  - ../../../../../base/hidsafeadapter

images:
    - name: hidsafeadapter-image
      newName: localhost:32000/safe/hid.iams.unob.adn8.0.safeadapter
      newTag: {{TAG}}

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: v1
      kind: Deployment
      metadata:
        name: hidsafeadapter
        namespace: {{clientname}}-{{envname}}
        labels:
          namespace-name: '{{clientname}}-{{envname}}'
          deployment-env: '{{envname}}'
          deployment-instance: 'local'
      spec:
        selector:
          matchLabels:
            namespace-name: '{{clientname}}-{{envname}}'
            deployment-env: '{{envname}}'
            deployment-instance: 'local'
        template:
          metadata:
            labels:
              namespace-name: '{{clientname}}-{{envname}}'
              deployment-env: '{{envname}}'
              deployment-instance: 'local'
          spec:
            containers:
            - name: hidsafeadapter
            volumes:
            - name: config-volume
              hostPath:
                path: /usr/local/share/source/repos/safe_vnext/Src/Container/config
            - name: log-volume
              hostPath:
                path: /usr/local/share/runlogs

  - target:
      kind: Job
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: hidsafeadapter-presync-status
        labels:
          namespace-name: '{{clientname}}-{{envname}}'
          deployment-env: '{{envname}}'
          deployment-instance: 'local'
      spec:
        template:
          spec:
            containers:
            - name: presync-status-container
              env:
              - name: CLIENT
                value: "{{clientname}}"
              - name: ENV
                value: "{{envname}}"