apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -hid-onprem
resources:
  - ../../../../../base/presynclock

patches:
  - target:
      kind: CustomResourceDefinition
    patch: |-
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: hidsafe-presynclock
        labels:
          namespace-name: {{clientname}}-{{envname}}
          deployment-env: {{envname}}
          deployment-instance: 'local'

  - target:
      kind: PreSyncLock
    patch: |-
      apiVersion: v1
      kind: PreSyncLock
      metadata:
        name: hidsafe-presynclock-status
        namespace: {{clientname}}-{{envname}}
        labels:
          namespace-name: {{clientname}}-{{envname}}
          deployment-env: {{envname}}
          deployment-instance: 'local'

